spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ekivoki
    username: root
    password: root

springdoc:
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /api-ui